// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Normas.Api.Data;

namespace Normas.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210514233045_Initialize")]
    partial class Initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Normas")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Normas.Api.Models.Norma", b =>
                {
                    b.Property<int>("NormaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("TipoRequisitoId")
                        .HasColumnType("int");

                    b.HasKey("NormaID");

                    b.HasIndex("TipoRequisitoId");

                    b.ToTable("Normas");

                    b.HasData(
                        new
                        {
                            NormaID = 1,
                            Activo = true,
                            Clave = "abc123",
                            Descripcion = "descripcion",
                            FechaPublicacion = new DateTime(2021, 5, 14, 18, 30, 45, 163, DateTimeKind.Local).AddTicks(2021),
                            TipoRequisitoId = 1
                        },
                        new
                        {
                            NormaID = 2,
                            Activo = true,
                            Clave = "abc123",
                            Descripcion = "descripcion",
                            FechaPublicacion = new DateTime(2021, 5, 14, 18, 30, 45, 167, DateTimeKind.Local).AddTicks(4797),
                            TipoRequisitoId = 1
                        });
                });

            modelBuilder.Entity("Normas.Api.Models.TipoRequisito", b =>
                {
                    b.Property<int>("TipoRequisitoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TipoRequisitoId");

                    b.ToTable("TipoRequisitos");

                    b.HasData(
                        new
                        {
                            TipoRequisitoId = 1,
                            Descripcion = "Norma Oficial Mexicana (NOM)"
                        },
                        new
                        {
                            TipoRequisitoId = 2,
                            Descripcion = "Especificacion CFE"
                        },
                        new
                        {
                            TipoRequisitoId = 3,
                            Descripcion = "Reglamento Federal"
                        },
                        new
                        {
                            TipoRequisitoId = 4,
                            Descripcion = "Reglamento Estatal"
                        },
                        new
                        {
                            TipoRequisitoId = 5,
                            Descripcion = "Reglamento Municipal"
                        },
                        new
                        {
                            TipoRequisitoId = 6,
                            Descripcion = "Estandar Internacional"
                        },
                        new
                        {
                            TipoRequisitoId = 7,
                            Descripcion = "Norma de Referencia"
                        },
                        new
                        {
                            TipoRequisitoId = 8,
                            Descripcion = "Norma Mexicana"
                        });
                });

            modelBuilder.Entity("Normas.Api.Models.Norma", b =>
                {
                    b.HasOne("Normas.Api.Models.TipoRequisito", "Requisito")
                        .WithMany()
                        .HasForeignKey("TipoRequisitoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Requisito");
                });
#pragma warning restore 612, 618
        }
    }
}
